# This file is meant for configuring the main
# aspects of Enchantment Forge, and can only
# be changed directly.
#
# To reload this file use /ef update configuration

Debug-exceptions: false
Enchantment-settings:
  log-registrations: false
  log-errors: true
  import-new: true
Essence-settings:
  item:
    material: DRAGON_BREATH
    name: '&e%amount% &d&nLiquid Essence'
    lore:
    - ''
    - '&8- &4&oThis bottle contains liquid essence'
    - '&4&ofrom enchantment orbs that were'
    - '&4&osalvaged during merging.'
    - '&8- &4&oAll wise enchantments use essence'
    - '&4&oas price for using them.'
    glint: true
  limit-per-bottle: 100000
  limit-per-item: 10000
Slot-settings:
  item-regular:
    material: SLIME_BALL
    name: '&a&nEnchantment Slots&r &6(&e+%slots%&6)'
    lore:
    - ''
    - '&8- &2&oSlots are used to increase item'
    - '&2&oenchantment capacity.'
    - '&8- &2&oDrag and drop onto an item'
    - '&2&oto apply.'
    glint: true
  item-godly:
    material: MAGMA_CREAM
    name: '&c&nGodly Enchantment Slots&r &3(&b+%slots%&3)'
    lore:
    - ''
    - '&8- &9&oGodly slots are used to increase item'
    - '&9&oenchantment capacity for &4eternal &9&oand'
    - '&5wise &9&oenchantments.'
    - '&8- &9&oDrag and drop onto an item'
    - '&9&oto apply.'
    glint: true
  limit-regular: 10
  limit-godly: 5
  default-values:
    ALL:
      regular: 5
      godly: 1
    WOODEN_SWORD:
      regular: 3
      godly: 0
    WOODEN_PICKAXE:
      regular: 3
      godly: 0
    WOODEN_AXE:
      regular: 3
      godly: 0
    WOODEN_SHOVEL:
      regular: 3
      godly: 0
    WOODEN_HOE:
      regular: 3
      godly: 0
    LEATHER_BOOTS:
      regular: 3
      godly: 0
    LEATHER_LEGGINGS:
      regular: 3
      godly: 0
    LEATHER_CHESTPLATE:
      regular: 3
      godly: 0
    LEATHER_HELMET:
      regular: 3
      godly: 0
    STONE_SWORD:
      regular: 3
      godly: 0
    STONE_PICKAXE:
      regular: 3
      godly: 0
    STONE_AXE:
      regular: 3
      godly: 0
    STONE_SHOVEL:
      regular: 3
      godly: 0
    STONE_HOE:
      regular: 3
      godly: 0
    CHAINMAIL_BOOTS:
      regular: 3
      godly: 0
    CHAINMAIL_LEGGINGS:
      regular: 3
      godly: 0
    CHAINMAIL_CHESTPLATE:
      regular: 3
      godly: 0
    CHAINMAIL_HELMET:
      regular: 3
      godly: 0
    GOLDEN_SWORD:
      regular: 3
      godly: 0
    GOLDEN_PICKAXE:
      regular: 3
      godly: 0
    GOLDEN_AXE:
      regular: 3
      godly: 0
    GOLDEN_SHOVEL:
      regular: 3
      godly: 0
    GOLDEN_HOE:
      regular: 3
      godly: 0
    GOLDEN_BOOTS:
      regular: 3
      godly: 0
    GOLDEN_LEGGINGS:
      regular: 3
      godly: 0
    GOLDEN_CHESTPLATE:
      regular: 3
      godly: 0
    GOLDEN_HELMET:
      regular: 3
      godly: 0
    IRON_SWORD:
      regular: 4
      godly: 0
    IRON_PICKAXE:
      regular: 4
      godly: 0
    IRON_AXE:
      regular: 4
      godly: 0
    IRON_SHOVEL:
      regular: 4
      godly: 0
    IRON_HOE:
      regular: 4
      godly: 0
    IRON_BOOTS:
      regular: 4
      godly: 0
    IRON_LEGGINGS:
      regular: 4
      godly: 0
    IRON_CHESTPLATE:
      regular: 4
      godly: 0
    IRON_HELMET:
      regular: 4
      godly: 0
    DIAMOND_SWORD:
      regular: 4
      godly: 1
    DIAMOND_PICKAXE:
      regular: 4
      godly: 1
    DIAMOND_AXE:
      regular: 4
      godly: 1
    DIAMOND_SHOVEL:
      regular: 4
      godly: 1
    DIAMOND_HOE:
      regular: 4
      godly: 1
    DIAMOND_BOOTS:
      regular: 4
      godly: 1
    DIAMOND_LEGGINGS:
      regular: 4
      godly: 1
    DIAMOND_CHESTPLATE:
      regular: 4
      godly: 1
    DIAMOND_HELMET:
      regular: 4
      godly: 1
    NETHERITE_SWORD:
      regular: 5
      godly: 1
    NETHERITE_PICKAXE:
      regular: 5
      godly: 1
    NETHERITE_AXE:
      regular: 5
      godly: 1
    NETHERITE_SHOVEL:
      regular: 5
      godly: 1
    NETHERITE_HOE:
      regular: 5
      godly: 1
    NETHERITE_BOOTS:
      regular: 5
      godly: 1
    NETHERITE_LEGGINGS:
      regular: 5
      godly: 1
    NETHERITE_CHESTPLATE:
      regular: 5
      godly: 1
    NETHERITE_HELMET:
      regular: 5
      godly: 1
Station-settings:
  update-speed: MODERATE
  distance-between: 12
  time-out-ticks: 1800
  place-by-players: false
  destroy-by-players: false
Command-settings:
  essence-split:
    label: essencesplit
    description: Split essence from an item.
    aliases:
    - splitessence
  enchantment-info:
    label: enchantments
    description: Shows all enchantments.
    aliases:
    - enchants
    - enchantinfo
    - enchantmentinfo
  demolish-orbs:
    label: demolish
    description: Demolishes enchantment orbs.
    aliases:
    - demolishenchantment
    - enchantmentdemolish
    - enchantdemolish
  rename-item:
    label: renameitem
    description: Renames items.
    aliases:
    - itemrename
Renaming-settings:
  enabled: true
  length-limit: 20
  colors: abcdef1234567890
  price: experience_levels-1
  ignored: []
Restrictions:
  station-input-item: []
Inventories:
  demolish:
    result-empty:
      material: GLASS_BOTTLE
      name: '&6Insert enchantments to demolish'
    result-full:
      material: DRAGON_BREATH
      name: '&dEssence: &f%essence%'
      glint: true
    accept-invalid:
      material: BARRIER
      name: '&6Insert enchantments to demolish'
    accept-valid:
      material: EMERALD
      name: '&aDemolish enchantments into essence'
      glint: true
Configuration-version: 2
